shfmt all bash scripts

diff --git a/roles/user-term/files/scripts/vmlimit-exec b/roles/user-term/files/scripts/vmlimit-exec
--- a/roles/user-term/files/scripts/vmlimit-exec
+++ b/roles/user-term/files/scripts/vmlimit-exec
@@ -5,17 +5,17 @@ base=${0##*/}
 
 bin="/usr/bin/$base"
 if ! [ -x "$bin" ]; then
-    bin="/bin/$base"
+	bin="/bin/$base"
 fi
 if ! [ -x "$bin" ]; then
-    bin="/usr/sbin/$base"
+	bin="/usr/sbin/$base"
 fi
 if ! [ -x "$bin" ]; then
-    bin="/sbin/$base"
+	bin="/sbin/$base"
 fi
 if ! [ -x "$bin" ]; then
-    echo "$base" not found >&2
-    exit 1
+	echo "$base" not found >&2
+	exit 1
 fi
 
 exec "$bin" "$@"
